### ISSUE TITLE
1024x1024 res images render failed. 256 MB Metal Memory limit. 

### ISSUE THREAD

**Issue by Boca007** [amazingyyc/Brouhaha#1]
Hi Yan,

i must to say this is an amazing work. :) and thx for share. 

so i have a question. is this possible to render 1024x1024 res images? the app stop with the: failed assertion `newBufferWith*:length 0x112a8800 must not exceed 256 MB.' 
i red at Ur comment a the BrouConvolutionMM.metal file, this is the Metal memory limit. And you mention here too:
"so if the image is big, the BrouConvolutionLayer is a better choice"

can U tell me how can i do that please? 
thx very much.

Csaba

**Comment by amazingyyc** [comment]
because the memory limit of the Metal is 256Mb, so it will crash if u set s big image.
Go to the BrouhahaDemo find the file: ArtTransformHalfViewController.m, than change the BrouConvolutionMMLayer_half to BrouConvolutionLayer_half and BrouTransposedConvolutionMMLayer_half to BrouTransposedConvolutionLayer_half
u should change two place:one is at the begin of the file, another is in function - (void)initArtTransfrom

The same operate on the file:ArtTransformViewController.m

**Comment by Boca007** [comment]
Hi Yan, thx the infos, but it is not working for me. :((( can U tell me what am i doing wrong?

so here is the 
ArtTransformHalfViewController.m (16 bit render)

14    BrouConvolutionMMLayer_half *conv2;    ->    BrouConvolutionLayer_half *conv2;
18    BrouConvolutionMMLayer_half *conv3;    ->    BrouConvolutionLayer_half *conv3; 
389 conv2 = [[BrouConvolutionMMLayer_half alloc] initWithDevice:device    ->   conv2 = [[BrouConvolutionLayer_half alloc] initWithDevice:device
411  conv3 = [[BrouConvolutionMMLayer_half alloc] initWithDevice:device    ->   conv3 = [[BrouConvolutionLayer_half alloc] initWithDevice:device

is this correct?
thx very much

**Comment by amazingyyc** [comment]
another change:BrouTransposedConvolutionMMLayer_half to BrouTransposedConvolutionLayer_half

**Comment by Boca007** [comment]
yes. of course. sorry forget to write down, i lost to write the details. i did that too. and still memory limit problem. :( and i did the _float versions too at. the image is 1000x1000.  
actually with 16 bit the error message is:  Execution of the command buffer was aborted due to an error during execution. Internal Error (IOAF code -536870211)

**Comment by amazingyyc** [comment]
i found the error, I will find the reason as soon as possible

**Comment by Boca007** [comment]
woow. thx. ;)

**Comment by amazingyyc** [comment]
hi Csaba
I update the new code that fix one bug.
But there still is another bug and that bug looks weird. It do not fixed for now.

I test the code, 800X800 pic can be supported, the 1024X1024 is not correct.

I think i have to take a long time to fix it.

**Comment by amazingyyc** [comment]
use the ArtTransformHalfViewController (Artistic Style Transform Float16)

**Comment by Boca007** [comment]
Perfect Yan, thx. i will check it out now. ;)

**Comment by amazingyyc** [comment]
hi Csaba
I test the 1024X1024 pic. I found that if the Neural Network run the layers one by one, it will be correct. But if run at the same time (in one MTLCommandBuffer) it will be crash and no logs.
I do not know why, just guess: May be in one MTLCommandBuffer, the Metal cant not execute too long. I make the thread sleep for a while between layers and it will correct.
I have update the code, u can check it out.

**Comment by Boca007** [comment]
hey Yan, 
thx very much. i checked, and now it is working well!!! congratulation, and thx very very much again. ;) amazing work. ;)
