### ISSUE TITLE
what is Layout  of the Weight data?

### ISSUE THREAD

**Issue by cscyangj** [amazingyyc/Brouhaha#2]
1. Some Confuse about _inputChannelX4, _outputChannelX4?
2. If I set weight param by myself, how should i arrange the weight data? Out_Channel X Kernel_W x Kernel_H x Input_channel? Or how can i convert caffe params to the weight data needed?

**Comment by amazingyyc** [comment]
the weights params of Convolution of Brouhaha is (outputChannel, kernelH, kernelW, inputChannel)
outputChannel:channel of output, 
kernelH, kernelW:the height and width of convolutiuon
inputChannel: the channel of input

and _inputChannelX4, _outputChannelX4 means 2 numbers that is bigger or equal to intputChannel ans outputChannel and can be divided by 4. this is for speed.

**Comment by amazingyyc** [comment]
useing the caffe model, u must convert the caffe model to raw-float data.
then build the layer by yourself. u can find the code in BrouhahaDemo

**Comment by cscyangj** [comment]
@amazingyyc , Great.
