### ISSUE TITLE
Query of Input format?

### ISSUE THREAD

**Issue by cscyangj** [amazingyyc/Brouhaha#3]
Below is the code of example LeNet

`

    for (int i = 0; i < 28 * 28; ++i) {
        floatInput[4 * i] = input[i];
    }
    
    TensorShape inputShape;
    TensorShape outputShape;
    
    inputShape.dim0 = 28;
    inputShape.dim1 = 28;
    inputShape.dim2 = 4;
    
    outputShape.dim0 = 24;
    outputShape.dim1 = 24;
    outputShape.dim2 = 20;
    
    [_conv0 computeWithCommandBuffer:commandBuffer
                               input:_buffer0
                          inputShape:inputShape
                              output:_buffer1
                         outputShape:outputShape];

    inputShape = outputShape;

    outputShape.dim0 = 12;
    outputShape.dim1 = 12;
    outputShape.dim2 = 20;`
1. Why inputShape.dim2 need to be 4, for speed?  
2. So if i have output channel not equal multiple of 4, i need to make it to be equal to multiple of 4? After i change the output channel numbers, do i need to change the data for next layer?
3. How output is arranged of convolution layer?

**Comment by amazingyyc** [comment]
So if i have output channel not equal multiple of 4, i need to make it to be equal to multiple of 4?
When init the convolution layer's params like:
` _conv0 = [[BrouConvolutionMMLayer_float alloc] initWithDevice:_device
                                                        library:_library
                                                    floatKernel:w0
                                                      floatBias:NULL
                                                   inputChannel:1
                                                  outputChannel:20
                                                   kernelHeight:5
                                                    kernelWidth:5
                                                         padTop:0
                                                        padLeft:0
                                                        strideY:1
strideX:1];`
u just input the actual shape, Like above: inputChannel is 1.
But when u cumpute the output like:
`    [_conv0 computeWithCommandBuffer:commandBuffer
                               input:_buffer0
                          inputShape:inputShape
                              output:_buffer1
outputShape:outputShape];`
U have to make sure the input and output inner channel can be divided by 4 and the enough memeory to store the output and input data.

Like the convolution layer's output is (height=32, width=32, channel = 3). But when computing the result, u have to give it a shape is (32, 32, 4) and enough memery to store the result (ref file:BrouTemporaryBuffer).

**Comment by cscyangj** [comment]
So Can u help check my param setting of Convolution based network, I think there maybe wrong setting of input and network?

I check the output of convolution layer, which is not same as caffe.

[FSRCNNViewController.m.zip](https://github.com/amazingyyc/Brouhaha/files/1588616/FSRCNNViewController.m.zip)

**Comment by amazingyyc** [comment]
I will check it when off work.

**Comment by cscyangj** [comment]
thanks so much, @amazingyyc

**Comment by amazingyyc** [comment]
hi i hava seen u r code.
I find a problem is 
`   /**init temp buffer*/
    _buffer0 = [_device newBufferWithLength:11 * 11 * 4 * sizeof(float)
                                    options:MTLResourceCPUCacheModeDefaultCache | MTLResourceStorageModeShared];
    
    _buffer1 = [_device newBufferWithLength:21 * 21 * 32 * sizeof(float)
                                    options:MTLResourceCPUCacheModeDefaultCache | MTLResourceStorageModeShared];`

the _buffer0 and _buffer1 is temp buffer for the output. But u have a output's shape is (7, 7, 32)

it means the _buffer0 can not contain the output. U must make sure the buffer is bigger than the Metal output.
And if u use another Toolkit like caffe or tensoflow, u have to make sure your convolution weight's dimension  is (outputchannel, kernelHeight, kernelWidth, inoutChannel). and the Brouhaha's convolution is actualy is "Cross Correlation" not a real convolution in Math. the differnt is :https://www.youtube.com/watch?v=C3EEy8adxvc
So make sure the convolution weight is right.

**Comment by cscyangj** [comment]
I will check that, thanks.

**Comment by cscyangj** [comment]
1. I make the  input buffer big enough,  and result is the same;

2. I check the weight, because the shape of conv1 is (32,1,5,5) in caffe, It needed to be transposed to (32,5,5,1), after transpose(0, 2, 3, 1) as required, i found that data in memory should be same as caffe. so result still the same.

Is there any mistake i made?

**Comment by amazingyyc** [comment]
i found that data in memory should be same as caffe.

What's that mean? 
U can test like this: use one convlution layer, the same input and weight like caffe.
test output of one layer.
Brouhaha's input and output shape is :(height, width, channel)
But i remmeber that the caffe input is:(channel, height, width).
So make sure u have consider this case!
