### ISSUE TITLE
How to generate weight file?

### ISSUE THREAD

**Issue by Penelope1003** [amazingyyc/Brouhaha#4]
Hi,
I want to convert a pytorch model to weight file.  I know the layout of weight should be (outputChannel, kernelH, kernelW, inputChannel). 
The weight data should be saved as bytes? like f.write(session.run(w_conv1_p).tobytes())
Or can u provide weight save code?

**Comment by amazingyyc** [comment]
The weight data should be saved as bytes?
yes, the weight is dumped as float bytes.

I do not have a pytorch script to convert the weight, only have a simple tensorflow script (I can send you later).

by the way, the project has been deprecated.

**Comment by amazingyyc** [comment]
https://github.com/amazingyyc/Brouhaha/blob/master/read.py demo code for convert
